import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = function () {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Next.js</h1>
    </main>
  );
};

export default Home;
